<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.5.11</version>
		<relativePath/>
	</parent>

	<groupId>com.tl</groupId>
	<artifactId>ssb</artifactId>
	<version>1.0</version>
	<packaging>pom</packaging>

	<!--聚合子模块-->
	<modules>
		<module>admin</module>
		<module>common</module>
		<module>web</module>
	</modules>

	<!--指定版本号-->
	<properties>
		<java.version>17</java.version>
		<spring-boot.version>3.5.11</spring-boot.version>
		<mysql.version>8.0.30</mysql.version>
		<mybatis.version>3.0.5</mybatis.version>
		<lombok.version>1.18.38</lombok.version>
	</properties>

	<!--依赖管理-->
	<dependencyManagement>
		<dependencies>
			<!--测试-->
			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-starter-test</artifactId>
				<version>${spring-boot.version}</version>
				<scope>test</scope>
			</dependency>

			<!--MVC-->
			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-starter-web</artifactId>
				<version>${spring-boot.version}</version>
			</dependency>

			<!--mysql 驱动-->
			<dependency>
				<groupId>mysql</groupId>
				<artifactId>mysql-connector-java</artifactId>
				<version>${mysql.version}</version>
			</dependency>

			<!--mybatis 驱动-->
			<dependency>
				<groupId>org.mybatis.spring.boot</groupId>
				<artifactId>mybatis-spring-boot-starter</artifactId>
				<version>${mybatis.version}</version>
			</dependency>

			<!--lombok-->
			<dependency>
				<groupId>org.projectlombok</groupId>
				<artifactId>lombok</artifactId>
				<version>${lombok.version}</version>
			</dependency>
		</dependencies>
	</dependencyManagement>

</project>
