# web端用8080端口
server:
  port: 8080

spring:
  datasource:
    # 数据库基础配置
    url: jdbc:mysql://127.0.0.1:3306/tlive?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    # 数据库连接池
    hikari:
      pool-name: HikariCPDatasource # 连接池名字
      idle-timeout: 180000 # 空闲连接超时时间
      maximum-pool-size: 10 # 最大连接数上限
      auto-commit: true # 自动提交
      max-lifetime: 1800000 # 最大生命周期
      connection-timeout: 30000 # 连接超时时间

#mybatis 大小写转驼峰
mybatis:
  configuration:
    map-underscore-to-camel-case: true
